name: 'Generate Random Version'
description: 'Generates a random version number using UUID.'

inputs:
  prefix:
    description: 'Optional prefix to append to the generated version.'
    required: false

outputs:
  version:
    description: 'The generated version number.'

runs:
  using: 'composite'
  steps:
    - name: Run Python script
      run: python $GITHUB_ACTION_PATH/main.py "${{ inputs.prefix }}"
      shell: bash
